sudo: false
dist: "trusty"
language: "node_js"
cache:
  directories:
    - "node_modules"
before_install:
  - "npm -g install npm@4"
install: "npm install --no-optional"
jobs:
  include:
    - node_js: "6"
      script: "npm run test"
    - node_js: "8"
      script: "npm run test"
